### ISSUE TITLE
Clean UP & Dockerization eos65rt

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/eos65rt#6]
Please check that the model is working and refactor it model to the latest eos-template structure.
The workflows have already been updated, you can start by checking if the Actions have run successfully or changes need to be made

**Comment by HellenNamulinda** [comment]
@GemmaTuron,
This model couldn't work initially. both on [Colab](https://colab.research.google.com/drive/1yBH3tQVV6aUPiPD02QJDkWoV7FgVkqRs?usp=sharing) and CLI([eos65rt_fetch_1.log](https://github.com/ersilia-os/eos65rt/files/11860819/eos65rt_fetch_1.log)) because of package rdkit package conflicts. 
```
UnsatisfiableError: The following specifications were found to be incompatible with a past
explicit spec that is not an explicit spec in this operation (libstdcxx-ng):

  - rdkit=2020.03 -> cairo[version='>=1.16.0,<2.0.0a0'] -> libgcc-ng[version='>=10.3.0|>=12|>=9.4.0|>=9.3.0|>=4.9|>=11.2.0|>=7.2.0|>=8.4.0']
  - rdkit=2020.03 -> cairo[version='>=1.16.0,<2.0.0a0'] -> zlib[version='1.2.*|1.2.11|1.2.11.*|>=1.2.11,<1.3.0a0|>=1.2.12,<1.3.0a0|>=1.2.13,<1.3.0a0|1.2.8']
....
```
Colab fetch log with details of package conflict [eos65rt_colab_fetch1.log](https://github.com/ersilia-os/eos65rt/files/11860649/eos65rt_colab_fetch1.log)

I ressolved these conflicts by installing rdkit using pip instead of conda. And also followed the recommended order of installing the packages. 
The Docker file run commands were changed from 
```
RUN conda install -c conda-forge rdkit=2020.03
RUN pip install pandas
RUN pip install mordred
RUN pip install tensorflow==1.15
RUN pip install h5py==2.9.0
```
to
```
RUN pip install pandas
RUN pip install mordred
RUN pip install tensorflow==1.15.0
RUN pip install h5py==2.9.0
RUN pip install rdkit-pypi==2022.3.1
```
And the model worked.

**Comment by HellenNamulinda** [comment]
> @GemmaTuron, This model couldn't work initially. both on [Colab](https://colab.research.google.com/drive/1yBH3tQVV6aUPiPD02QJDkWoV7FgVkqRs?usp=sharing) and CLI([eos65rt_fetch_1.log](https://github.com/ersilia-os/eos65rt/files/11860819/eos65rt_fetch_1.log)) because of package rdkit package conflicts.
> 
> ```
> UnsatisfiableError: The following specifications were found to be incompatible with a past
> explicit spec that is not an explicit spec in this operation (libstdcxx-ng):
> 
>   - rdkit=2020.03 -> cairo[version='>=1.16.0,<2.0.0a0'] -> libgcc-ng[version='>=10.3.0|>=12|>=9.4.0|>=9.3.0|>=4.9|>=11.2.0|>=7.2.0|>=8.4.0']
>   - rdkit=2020.03 -> cairo[version='>=1.16.0,<2.0.0a0'] -> zlib[version='1.2.*|1.2.11|1.2.11.*|>=1.2.11,<1.3.0a0|>=1.2.12,<1.3.0a0|>=1.2.13,<1.3.0a0|1.2.8']
> ....
> ```
> 
> Colab fetch log with details of package conflict [eos65rt_colab_fetch1.log](https://github.com/ersilia-os/eos65rt/files/11860649/eos65rt_colab_fetch1.log)
> 
> I ressolved these conflicts by installing rdkit using pip instead of conda. And also followed the recommended order of installing the packages. The Docker file run commands were changed from
> 
> ```
> RUN conda install -c conda-forge rdkit=2020.03
> RUN pip install pandas
> RUN pip install mordred
> RUN pip install tensorflow==1.15
> RUN pip install h5py==2.9.0
> ```
> 
> to
> 
> ```
> RUN pip install pandas
> RUN pip install mordred
> RUN pip install tensorflow==1.15.0
> RUN pip install h5py==2.9.0
> RUN pip install rdkit-pypi==2022.3.1
> ```
> 
> And the model worked.

The model was tested locally and it fetched successfully, [eos65rt_fetch_2.log](https://github.com/ersilia-os/eos65rt/files/11860993/eos65rt_fetch_2.log)
👍 Model eos65rt fetched successfully!
And hte served model made predictions successfully,  [eos65rt_outpt.csv](https://github.com/ersilia-os/eos65rt/files/11860958/eos65rt_outpt.csv)
```
(ersilia) hellenah@hellenah-elitebook:~$ ersilia serve eos65rt
🚀 Serving model eos65rt: deepfl-logp

   URL: http://127.0.0.1:58959
   PID: 74594
   SRV: conda

👉 To run model:
   - run

💁 Information:
   - info
(ersilia) hellenah@hellenah-elitebook:~$ ersilia run -i "CCCOCCCC"
{
    "input": {
        "key": "YGZQJYIITOMTMD-UHFFFAOYSA-N",
        "input": "CCCOCCCC",
        "text": "CCCOCCCC"
    },
    "output": {
        "LogP": 2.755633
    }
}
(ersilia) hellenah@hellenah-elitebook:~$ ersilia run -i ~/input_15.csv -o eos65rt_outpt.csv
eos65rt_outpt.csv
```
These changes were pushed and are reflected in the pull request here - https://github.com/ersilia-os/eos65rt/pull/7

**Comment by HellenNamulinda** [comment]
Hi @GemmaTuron,
The build for amd64 was successful. However, arm64 build [failed](https://github.com/ersilia-os/eos65rt/actions/runs/5374444873/jobs/9749816346#step:7:2204) because of the old version of tensorflow used by this model.
`#8 729.2 ERROR: Could not find a version that satisfies the requirement tensorflow==1.15.0 (from versions: 2.10.0rc0, 2.10.0rc1, 2.10.0rc2, 2.10.0rc3, 2.10.0, 2.10.1, 2.11.0rc0, 2.11.0rc1, 2.11.0rc2, 2.11.0) `
Changing the tensorflow version will mean re-writing some functions in the model.

I hope it's okay if we left it at this point of not changing the tensorflow version.

**Comment by GemmaTuron** [comment]
yes, that's fine thanks @HellenNamulinda !
